version: "3.7"
services:
  api:
    build: .
    container_name: wiki_fetch-api
    ports:
      - "${APP_PORT:-10000}:10000"
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      ENABLE_RELOAD_UVICORN: ${ENABLE_RELOAD_UVICORN}
      POSTGRES_URL: ${POSTGRES_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ROOT_PATH: ""
    volumes:
      - ".:/srv"
    networks:
      - internal
    hostname: wiki_fetch
    depends_on:
      - "postgres"
  postgres:
    image: postgres:13.3
    container_name: wiki_fetch-postgres
    ports:
      - "${HOST_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - internal
    volumes:
      - "./migrations:/mnt"
      - ./0000_init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}
networks:
  internal:
    external: false
